#!/usr/bin/env bash

if [ "$#" -ne 4 ]; then
    echo "Usage: $(basename "$0") PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file="$1"
ip="$2"
user="$3"
key="$4"

scp -i "$key" -o StrictHostKeyChecking=no "$file" "$user"@"$ip":~/ 
