#!/usr/bin/env bash
# Intsalling nginx with the following:
# with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
apt -y update
apt -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start

