#!/usr/bin/env bash
# Install and configure HAproxy
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.8 -y
apt-get install haproxy -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 100.26.50.2:80 check
        server web2 35.175.65.7:80 check
" | tee -a /etc/haproxy/haproxy.cfg
service haproxy restart

