#!/usr/bin/env bash
#this bash script will accept an arg and pass it to the command ping and pisg the ip 5 times
if [ $# -lt 1 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi

