#!/usr/bin/env bash
#this bash script will accept an arg and pass it to the command ping and pisg the ip 5 times
i=1
if [ $# -gt 1 ]
then
	while [ $i -lt 5 ]
		do
			ping "$1"
			((i++))
		done
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi

