#!/usr/bin/env bash
#Bash script that displays: To infinity and beyond indefinitely, With a sleep 2 in between each iteration, I am invincible!!! when receiving a SIGTERM signal.
i=1
print_upon_recv_singal()
{
	echo "I am invincible!!!"
}
trap print_upon_recv_singal SIGTERM
while [ $i == 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done
