#!/usr/bin/env bash
#a Bash script that displays:The content of the current directory,In a list format,Where only the part of the name after the first dash is displayed
name_of_file=""
for file in *;
do
	if [ -f "$file" ] && [[ "$file" != .* ]]
	then
		name_of_file=${file#*-}
		echo "$name_of_file"
	fi
done
